### ISSUE TITLE
Outline shows around title text after opening an announcement

### ISSUE THREAD

**Issue by shickey** [BlakeCS-Spring2017/BearHug#3]
After tapping an announcement title to display the rest of the announcement, a orange outline appears around the announcement title text (when viewed in mobile on Chrome; it appears blue when not in mobile mode). This outline should never appear at any point when using the app.

Screenshot:
![screen shot 2017-04-18 at 8 07 20 pm](https://cloud.githubusercontent.com/assets/1489558/25159105/00cbc156-2473-11e7-9c9d-b1ed68c3b176.png)

Steps to reproduce:
1. Start the app
2. Navigate to the announcement tab
3. Tap on the title text for any announcement
4. See the gross orange/blue outline

**Comment by ebroe18** [comment]
Fixed with commit 6f32167
