### ISSUE TITLE
Unable to scroll far enough for the bottom announcement to be visible above the taskbar. Additionally, the triangles go above the taskbar

### ISSUE THREAD

**Issue by sabrandt17** [BlakeCS-Spring2017/BearHug#4]
If enough announcements are on screen so that they end up behind the taskbar, the bottom announcement will stuck behind the taskbar because you will be unable to scroll far enough to make it visible.
Additionally, the triangle buttons are layered on top of the taskbar. 

Screenshot:
![screen shot 2017-04-20 at 12 57 04 pm](https://cloud.githubusercontent.com/assets/25821957/25245243/67cf1824-25c9-11e7-8872-d6f85bd85616.png)
Unable to scroll up to view the obscured announcement, triangle is above taskbar.

Steps to reproduce:
1. Start the app
2. Navigate to the announcements tab
3. Click on any announcement to expand it
3. Notice you will be unable to scroll down to see the whole bottom announcement
4. Notice the triangle of the bottom announcement on the taskbar
5. Be sad about it

**Comment by sjellis18** [comment]
I figured out how to fix the triangle going over the taskbar and all you have to add is z-index: 1; to the ul css in taskbar.css. I will continue to try and get it so that we can see the whole announcement when it is cut off

**Comment by sjellis18** [comment]
I just figured out how to get it so the last announcement isn't lost!!! yayayaya!!!

**Comment by shickey** [comment]
Solved in 2bb325e
